Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.box = 'centos/7'
  config.vm.hostname = 'gitlab'
  config.vm.network "private_network", ip: "10.10.1.70"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    v.memory =1048
  end
  
end
