Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

    config.vm.box = 'centos/7'
    config.vm.hostname = 'manager'
    config.vm.network "private_network", ip: "10.10.1.50"
    config.vm.provider 'virtualbox' do |v| 
      v.memory =2048
    end
    
  end