Vagrant.configure("2") do |config| 

    if Vagrant.has_plugin?("vagrant-vbguest") then
        config.vbguest.auto_update = false
    end

    config.vm.provision "shell", inline: "echo Config docker swarm cluster"
    config.vm.define "manager" do |manager| 
        manager.vm.box = "centos/7"
        manager.vm.hostname = "manager"
        manager.vm.provision "shell", path: "provision.sh"
        manager.vm.network "private_network", ip: "10.10.1.12"
        manager.vm.network "forwarded_port", guest: 80, host: 8090
    end
    config.vm.define "worker1" do |worker1| 
        worker1.vm.box = "centos/7"
        worker1.vm.hostname = "worker1"
        worker1.vm.provision "shell", path: "provision.sh"
        worker1.vm.network "private_network", ip: "10.10.1.13"
    end
    config.vm.define "worker2" do |worker2| 
        worker2.vm.box = "centos/7"
        worker2.vm.hostname = "worker2"
        worker2.vm.provision "shell", path: "provision.sh"
        worker2.vm.network "private_network", ip: "10.10.1.14"
    end
end
